---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: !!!little-help-book
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: little-help-book-exporter
          image: mvpstudio/little-help-book-exporter:2021-01-12
          resources:
            limits:
              cpu: 0.25
              memory: 100Mi
            requests:
              cpu: 0.25
              memory: 100Mi
          ports:
            - containerPort: 5000
          env:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: !!!little-help-book
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000